modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="ordemparanormal"
version="${file.jarVersion}"
displayName="Ordem Paranormal"
logoFile="ordemparanormal.png"
credits="Obrigado Rafael Lange por criar o universo de Ordem Paranormal e Lye por criar as texturas."
authors="Guga"
description='''O Paranormal não vem para a nossa realidade facilmente, ou pelo menos deveria ser assim...'''
[[dependencies.ordemparanormal]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ordemparanormal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ordemparanormal]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.3.2,)"
    ordering = "BEFORE"
    side = "BOTH"